server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding: # 设置编码 CharacterEncodingFilter
      force: true
      enabled: true
      charset: utf-8
    context-path: /producer



rocketmq:
  name-server: 192.168.5.128:9876
  producer:
    group: my-producer-group


